# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/lucas/OneDrive/PhD/NexysDDR4 tutorial/2015_2_artix7_sources/lab1/lab1.cache/wt} [current_project]
set_property parent.project_path {C:/Users/lucas/OneDrive/PhD/NexysDDR4 tutorial/2015_2_artix7_sources/lab1/lab1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo {c:/Users/lucas/OneDrive/PhD/NexysDDR4 tutorial/2015_2_artix7_sources/lab1/lab1.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {{C:/Users/lucas/OneDrive/PhD/NexysDDR4 tutorial/2015_2_artix7_sources/lab1/lab1.v}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/lucas/OneDrive/PhD/NexysDDR4 tutorial/2015_2_artix7_sources/lab1/lab1_nexys4_ddr.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/lucas/OneDrive/PhD/NexysDDR4 tutorial/2015_2_artix7_sources/lab1/lab1_nexys4_ddr.xdc}}]


synth_design -top lab1 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef lab1.dcp

catch { report_utilization -file lab1_utilization_synth.rpt -pb lab1_utilization_synth.pb }
